graph [
  node [
    id 0
    label "0"
    name "Medieval Literature: Dante, Boccaccio, Chaucer"
    topics "Humanities"
    topics "History"
    topics "Medieval History"
    topics "Literature"
    topics "Comparative Literature"
    topics "Criticism"
    topics "Humanities"
    topics "History"
    topics "Medieval History"
    topics "Literature"
    topics "Comparative Literature"
    topics "Criticism"
    description "The course explores the literary masterworks of three of the most celebrated authors of the Middle A..."
  ]
  node [
    id 1
    label "1"
    name "Topics in Statistics: Statistical Learning Theory"
    topics "Engineering"
    topics "Computer Science"
    topics "Algorithms and Data Structures"
    topics "Artificial Intelligence"
    topics "Mathematics"
    topics "Probability and Statistics"
    topics "Science"
    topics "Cognitive Science"
    topics "Engineering"
    topics "Computer Science"
    topics "Algorithms and Data Structures"
    topics "Artificial Intelligence"
    topics "Mathematics"
    topics "Probability and Statistics"
    topics "Science"
    topics "Cognitive Science"
    description "No description found."
  ]
  node [
    id 2
    label "2"
    name "Media and Methods: Seeing and Expression"
    topics "Fine Arts"
    topics "Media Studies"
    topics "Digital Media"
    topics "Visual Arts"
    topics "Graphic Design"
    topics "Fine Arts"
    topics "Media Studies"
    topics "Digital Media"
    topics "Visual Arts"
    topics "Graphic Design"
    description "In this course students create digital visual images and analyze designs from historical and theoret..."
  ]
  node [
    id 3
    label "3"
    name "Strange Bedfellows: Science and Environmental Policy"
    topics "Engineering"
    topics "Environmental Engineering"
    topics "Environmental Management"
    topics "Science"
    topics "Earth Science"
    topics "Environmental Science"
    topics "Social Science"
    topics "Public Administration"
    topics "Environmental Policy"
    topics "Engineering"
    topics "Environmental Engineering"
    topics "Environmental Management"
    topics "Science"
    topics "Earth Science"
    topics "Environmental Science"
    topics "Social Science"
    topics "Public Administration"
    topics "Environmental Policy"
    description "12.103 explores the role of scientific knowledge, discovery, method, and argument in environmental p..."
  ]
  node [
    id 4
    label "4"
    name "Doctoral Seminar in Engineering Systems"
    topics "Engineering"
    topics "Systems Engineering"
    topics "Engineering"
    topics "Systems Engineering"
    description "IDS.900 Doctoral Seminar in Engineering Systems examines the core theory and contextual applications..."
  ]
  node [
    id 5
    label "5"
    name "The Conquest of America"
    topics "Humanities"
    topics "History"
    topics "American History"
    topics "Social Science"
    topics "Anthropology"
    topics "Cultural Anthropology"
    topics "Society"
    topics "Indigenous Studies"
    topics "Humanities"
    topics "History"
    topics "American History"
    topics "Social Science"
    topics "Anthropology"
    topics "Cultural Anthropology"
    topics "Society"
    topics "Indigenous Studies"
    description "In this course the conquest and colonization of the Americas is considered, with special attention t..."
  ]
  node [
    id 6
    label "6"
    name "Spanish IV"
    topics "Humanities"
    topics "Language"
    topics "Spanish"
    topics "Humanities"
    topics "Language"
    topics "Spanish"
    description "Course Sequences&#10;Spanish IV aims at developing and improving student&#8217;s oral and written communicatio..."
  ]
  node [
    id 7
    label "7"
    name "LL EduCATE: Introduction to Engineering Concepts"
    topics "Engineering"
    topics "Engineering"
    description "Welcome to &#8220;Introduction to Engineering Concepts,&#34; a lesson that will introduce you to several STEM ..."
  ]
  node [
    id 8
    label "8"
    name "Nuclear Weapons Education Project"
    topics "Energy"
    topics "Nuclear"
    topics "Humanities"
    topics "History"
    topics "History of Science and Technology"
    topics "Science"
    topics "Physics"
    topics "Atomic, Molecular, Optical Physics"
    topics "Energy"
    topics "Nuclear"
    topics "Humanities"
    topics "History"
    topics "History of Science and Technology"
    topics "Science"
    topics "Physics"
    topics "Atomic, Molecular, Optical Physics"
    description "No description found."
  ]
  node [
    id 9
    label "9"
    name "The History of MIT"
    topics "Humanities"
    topics "History"
    topics "American History"
    topics "History of Science and Technology"
    topics "Modern History"
    topics "Teaching and Education"
    topics "Higher Education"
    topics "Humanities"
    topics "History"
    topics "American History"
    topics "History of Science and Technology"
    topics "Modern History"
    topics "Teaching and Education"
    topics "Higher Education"
    description "This course examines the history of MIT through the lens of the broader history of science and techn..."
  ]
  node [
    id 10
    label "10"
    name "Near-Surface Geophysical Imaging"
    topics "Engineering"
    topics "Computer Science"
    topics "Data Mining"
    topics "Science"
    topics "Earth Science"
    topics "Geology"
    topics "Geophysics"
    topics "Engineering"
    topics "Computer Science"
    topics "Data Mining"
    topics "Science"
    topics "Earth Science"
    topics "Geology"
    topics "Geophysics"
    description "This graduate level course presents theories, methodologies, and applications of seismic imaging for..."
  ]
  node [
    id 11
    label "11"
    name "Musical Improvisation"
    topics "Fine Arts"
    topics "Music"
    topics "Fine Arts"
    topics "Music"
    description "In this course, students study concepts and practice techniques of improvisation in solo and ensembl..."
  ]
  node [
    id 12
    label "12"
    name "Data Communication Networks"
    topics "Engineering"
    topics "Computer Science"
    topics "Computer Networks"
    topics "Electrical Engineering"
    topics "Telecommunications"
    topics "Engineering"
    topics "Computer Science"
    topics "Computer Networks"
    topics "Electrical Engineering"
    topics "Telecommunications"
    description "6.263J / 16.37J focuses on the fundamentals of data communication networks. One goal is to give some..."
  ]
  node [
    id 13
    label "13"
    name "Learn to Build Your Own Videogame with the Unity Game Engine and Microsoft Kinect"
    topics "Engineering"
    topics "Computer Science"
    topics "Graphics and Visualization"
    topics "Software Design and Engineering"
    topics "Fine Arts"
    topics "Game Design"
    topics "Media Studies"
    topics "Digital Media"
    topics "Engineering"
    topics "Computer Science"
    topics "Graphics and Visualization"
    topics "Software Design and Engineering"
    topics "Fine Arts"
    topics "Game Design"
    topics "Media Studies"
    topics "Digital Media"
    description "This is a 9-day hands-on workshop about designing, building, and publishing simple educational video..."
  ]
  node [
    id 14
    label "14"
    name "Civic Media Codesign Studio"
    topics "Social Science"
    topics "Communication"
    topics "Public Administration"
    topics "Public Policy"
    topics "Social Welfare"
    topics "Social Science"
    topics "Communication"
    topics "Public Administration"
    topics "Public Policy"
    topics "Social Welfare"
    description "The Civic Media Codesign Studio is a project-based studio course in collaborative design of civic me..."
  ]
  node [
    id 15
    label "15"
    name "Weight Training"
    topics "Health and Medicine"
    topics "Health and Exercise Science"
    topics "Physical Education and Recreation"
    topics "Health and Medicine"
    topics "Health and Exercise Science"
    topics "Physical Education and Recreation"
    description "No description found."
  ]
  node [
    id 16
    label "16"
    name "Marketing Management: Analytics, Frameworks, and Applications"
    topics "Business"
    topics "Management"
    topics "Marketing"
    topics "Business"
    topics "Management"
    topics "Marketing"
    description "This course helps students develop skills in marketing analysis and planning, and introduces key mar..."
  ]
  node [
    id 17
    label "17"
    name "Project Laboratory in Mathematics"
    topics "Mathematics"
    topics "Mathematics"
    description "Project Laboratory in Mathematics is a course designed to give students a sense of what it&#8217;s like to..."
  ]
  node [
    id 18
    label "18"
    name "Microelectronic Devices and Circuits"
    topics "Engineering"
    topics "Computer Science"
    topics "Computer Design and Engineering"
    topics "Electrical Engineering"
    topics "Electronics"
    topics "Engineering"
    topics "Computer Science"
    topics "Computer Design and Engineering"
    topics "Electrical Engineering"
    topics "Electronics"
    description "6.012 is the header course for the department&#8217;s &#8220;Devices, Circuits and Systems&#8221; concentration. The t..."
  ]
  node [
    id 19
    label "19"
    name "Groundwater Hydrology"
    topics "Engineering"
    topics "Environmental Engineering"
    topics "Hydrology and Water Resource Systems"
    topics "Science"
    topics "Earth Science"
    topics "Geology"
    topics "Engineering"
    topics "Environmental Engineering"
    topics "Hydrology and Water Resource Systems"
    topics "Science"
    topics "Earth Science"
    topics "Geology"
    description "No description found."
  ]
  edge [
    source 0
    target 5
